// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: is_message.proto

#ifndef PROTOBUF_is_5fmessage_2eproto__INCLUDED
#define PROTOBUF_is_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_is_5fmessage_2eproto();
void protobuf_AssignDesc_is_5fmessage_2eproto();
void protobuf_ShutdownFile_is_5fmessage_2eproto();

class CMsgIncrementKillCountAttribute;

enum ECsgoGCMsg {
  k_EMsgGC_IncrementKillCountAttribute = 1074
};
bool ECsgoGCMsg_IsValid(int value);
const ECsgoGCMsg ECsgoGCMsg_MIN = k_EMsgGC_IncrementKillCountAttribute;
const ECsgoGCMsg ECsgoGCMsg_MAX = k_EMsgGC_IncrementKillCountAttribute;
const int ECsgoGCMsg_ARRAYSIZE = ECsgoGCMsg_MAX + 1;

const ::google::protobuf::EnumDescriptor* ECsgoGCMsg_descriptor();
inline const ::std::string& ECsgoGCMsg_Name(ECsgoGCMsg value) {
  return ::google::protobuf::internal::NameOfEnum(
    ECsgoGCMsg_descriptor(), value);
}
inline bool ECsgoGCMsg_Parse(
    const ::std::string& name, ECsgoGCMsg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ECsgoGCMsg>(
    ECsgoGCMsg_descriptor(), name, value);
}
// ===================================================================

class CMsgIncrementKillCountAttribute : public ::google::protobuf::Message {
 public:
  CMsgIncrementKillCountAttribute();
  virtual ~CMsgIncrementKillCountAttribute();

  CMsgIncrementKillCountAttribute(const CMsgIncrementKillCountAttribute& from);

  inline CMsgIncrementKillCountAttribute& operator=(const CMsgIncrementKillCountAttribute& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgIncrementKillCountAttribute& default_instance();

  void Swap(CMsgIncrementKillCountAttribute* other);

  // implements Message ----------------------------------------------

  CMsgIncrementKillCountAttribute* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgIncrementKillCountAttribute& from);
  void MergeFrom(const CMsgIncrementKillCountAttribute& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 killer_account_id = 1;
  inline bool has_killer_account_id() const;
  inline void clear_killer_account_id();
  static const int kKillerAccountIdFieldNumber = 1;
  inline ::google::protobuf::uint32 killer_account_id() const;
  inline void set_killer_account_id(::google::protobuf::uint32 value);

  // optional fixed32 victim_account_id = 2;
  inline bool has_victim_account_id() const;
  inline void clear_victim_account_id();
  static const int kVictimAccountIdFieldNumber = 2;
  inline ::google::protobuf::uint32 victim_account_id() const;
  inline void set_victim_account_id(::google::protobuf::uint32 value);

  // optional uint64 item_id = 3;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 3;
  inline ::google::protobuf::uint64 item_id() const;
  inline void set_item_id(::google::protobuf::uint64 value);

  // optional uint32 event_type = 4;
  inline bool has_event_type() const;
  inline void clear_event_type();
  static const int kEventTypeFieldNumber = 4;
  inline ::google::protobuf::uint32 event_type() const;
  inline void set_event_type(::google::protobuf::uint32 value);

  // optional uint32 amount = 5;
  inline bool has_amount() const;
  inline void clear_amount();
  static const int kAmountFieldNumber = 5;
  inline ::google::protobuf::uint32 amount() const;
  inline void set_amount(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CMsgIncrementKillCountAttribute)
 private:
  inline void set_has_killer_account_id();
  inline void clear_has_killer_account_id();
  inline void set_has_victim_account_id();
  inline void clear_has_victim_account_id();
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_event_type();
  inline void clear_has_event_type();
  inline void set_has_amount();
  inline void clear_has_amount();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 killer_account_id_;
  ::google::protobuf::uint32 victim_account_id_;
  ::google::protobuf::uint64 item_id_;
  ::google::protobuf::uint32 event_type_;
  ::google::protobuf::uint32 amount_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_is_5fmessage_2eproto();
  friend void protobuf_AssignDesc_is_5fmessage_2eproto();
  friend void protobuf_ShutdownFile_is_5fmessage_2eproto();

  void InitAsDefaultInstance();
  static CMsgIncrementKillCountAttribute* default_instance_;
};
// ===================================================================


// ===================================================================

// CMsgIncrementKillCountAttribute

// optional fixed32 killer_account_id = 1;
inline bool CMsgIncrementKillCountAttribute::has_killer_account_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgIncrementKillCountAttribute::set_has_killer_account_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgIncrementKillCountAttribute::clear_has_killer_account_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgIncrementKillCountAttribute::clear_killer_account_id() {
  killer_account_id_ = 0u;
  clear_has_killer_account_id();
}
inline ::google::protobuf::uint32 CMsgIncrementKillCountAttribute::killer_account_id() const {
  return killer_account_id_;
}
inline void CMsgIncrementKillCountAttribute::set_killer_account_id(::google::protobuf::uint32 value) {
  set_has_killer_account_id();
  killer_account_id_ = value;
}

// optional fixed32 victim_account_id = 2;
inline bool CMsgIncrementKillCountAttribute::has_victim_account_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgIncrementKillCountAttribute::set_has_victim_account_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgIncrementKillCountAttribute::clear_has_victim_account_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgIncrementKillCountAttribute::clear_victim_account_id() {
  victim_account_id_ = 0u;
  clear_has_victim_account_id();
}
inline ::google::protobuf::uint32 CMsgIncrementKillCountAttribute::victim_account_id() const {
  return victim_account_id_;
}
inline void CMsgIncrementKillCountAttribute::set_victim_account_id(::google::protobuf::uint32 value) {
  set_has_victim_account_id();
  victim_account_id_ = value;
}

// optional uint64 item_id = 3;
inline bool CMsgIncrementKillCountAttribute::has_item_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgIncrementKillCountAttribute::set_has_item_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgIncrementKillCountAttribute::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgIncrementKillCountAttribute::clear_item_id() {
  item_id_ = GOOGLE_ULONGLONG(0);
  clear_has_item_id();
}
inline ::google::protobuf::uint64 CMsgIncrementKillCountAttribute::item_id() const {
  return item_id_;
}
inline void CMsgIncrementKillCountAttribute::set_item_id(::google::protobuf::uint64 value) {
  set_has_item_id();
  item_id_ = value;
}

// optional uint32 event_type = 4;
inline bool CMsgIncrementKillCountAttribute::has_event_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgIncrementKillCountAttribute::set_has_event_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgIncrementKillCountAttribute::clear_has_event_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgIncrementKillCountAttribute::clear_event_type() {
  event_type_ = 0u;
  clear_has_event_type();
}
inline ::google::protobuf::uint32 CMsgIncrementKillCountAttribute::event_type() const {
  return event_type_;
}
inline void CMsgIncrementKillCountAttribute::set_event_type(::google::protobuf::uint32 value) {
  set_has_event_type();
  event_type_ = value;
}

// optional uint32 amount = 5;
inline bool CMsgIncrementKillCountAttribute::has_amount() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgIncrementKillCountAttribute::set_has_amount() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgIncrementKillCountAttribute::clear_has_amount() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgIncrementKillCountAttribute::clear_amount() {
  amount_ = 0u;
  clear_has_amount();
}
inline ::google::protobuf::uint32 CMsgIncrementKillCountAttribute::amount() const {
  return amount_;
}
inline void CMsgIncrementKillCountAttribute::set_amount(::google::protobuf::uint32 value) {
  set_has_amount();
  amount_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ECsgoGCMsg>() {
  return ::ECsgoGCMsg_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_is_5fmessage_2eproto__INCLUDED
